# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b0dcb1623548caad6a8d3184ee3a6dfa64e14863df5ed3d4311c5ee5c1703bd44497547087176fc0ff849795cb2036fc38128c0ac7f1220df8b84f776dee62d

test:
  secret_key_base: c02052f35f020b07db85d0d7f04055098adac585268beb4ec64cc6b3713301bca49ae59de204a292dab7214f14dd6ba8f81a92644187b60f0526db6db30fbfd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
